-------------------------------------------------------------
-- USERS
-------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    create_at TIMESTAMP
);

-------------------------------------------------------------
-- SERVICE TYPES
-------------------------------------------------------------
CREATE TABLE IF NOT EXISTS service_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description JSON,
    create_at TIMESTAMP
);

-------------------------------------------------------------
-- TRUCK TYPES
-------------------------------------------------------------
CREATE TABLE IF NOT EXISTS truck_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    models VARCHAR(255),
    brand VARCHAR(255),
    load INTEGER,
    load_unit VARCHAR(25) NOT NULL,
    description VARCHAR(500)
);

-------------------------------------------------------------
-- ORDERS (đã tích hợp trips)
-------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

-- thông tin khách hàng
customer_name VARCHAR(255) NOT NULL,
customer_phone VARCHAR(20) NOT NULL,

-- loại dịch vụ
service_type_id INTEGER NOT NULL,

-- thông tin hàng hóa
weight INTEGER NOT NULL, weight_unit VARCHAR(25) NOT NULL,

-- nơi đi - nơi đến
from_location VARCHAR(255) NOT NULL,
to_location VARCHAR(255) NOT NULL,

-- trạng thái đơn
status VARCHAR(25) NOT NULL,

-- thời gian đặt
create_at DATE NOT NULL,

-- bổ sung từ TRIPS
truck_type_id INTEGER NOT NULL, duration VARCHAR(50) );

-------------------------------------------------------------
-- NEWS CATEGORIES
-------------------------------------------------------------
CREATE TABLE IF NOT EXISTS news_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-------------------------------------------------------------
-- NEWS
-------------------------------------------------------------
CREATE TABLE IF NOT EXISTS news (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    slug VARCHAR(500) NOT NULL,
    thumnail VARCHAR(255),
    content JSON,
    category_id INTEGER NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-------------------------------------------------------------
-- FOREIGN KEYS
-------------------------------------------------------------

-- orders → service types
ALTER TABLE orders
ADD CONSTRAINT fk_orders_service_type FOREIGN KEY (service_type_id) REFERENCES service_types (id);

-- orders → truck types
ALTER TABLE orders
ADD CONSTRAINT fk_orders_truck_type FOREIGN KEY (truck_type_id) REFERENCES truck_types (id);

-- news → news categories
ALTER TABLE news
ADD CONSTRAINT fk_news_category FOREIGN KEY (category_id) REFERENCES news_categories (id);